### ISSUE TITLE
Subfolders with unique sidebar?

### ISSUE THREAD

**Issue by znck** [serenohq/extension-docs#1]
Currently the sidebar file `/docs/documentation.md` are loaded for all docs files, even if it's in a subfolder that have another `documentation.md` file in it.

Structure:
```
.
+-- docs
|   +-- foo.md
|   +-- documentation.md
|   +-- subdoc
|   |   +-- bar.md
|   |   +-- documentation.md
```

> Copy from serenohq/extension-blog#1 ( @marktopper )

**Comment by marktopper** [comment]
I have done this in my own application.

Will send a pull request.

**Comment by znck** [comment]
Thanks in advance 🥇

**Comment by marktopper** [comment]
I have made this in #3

**Comment by marktopper** [comment]
This should be closed! 👍
