### ISSUE TITLE
Redirecting subfolders

### ISSUE THREAD

**Issue by marktopper** [serenohq/extension-docs#2]
Currently visiting `/docs` shows the content of `/docs/installation.md`.
However visiting `/docs/subdoc` does not show the content of `/docs/subdoc/installation.md`.

Would that be ideal?

Also, would it be possible to direct from `/docs` to `/docs/installation.md` instead of showing its content?

Structure:
```
.
+-- docs
|   +-- installation.md
|   +-- documentation.md
|   +-- subdoc
|   |   +-- installation.md
|   |   +-- documentation.md
```

If this is approved I can try make a pull request for this with configurations.

**Comment by znck** [comment]
It can be made configurable. Only way to redirect is meta refresh (https://www.w3.org/TR/WCAG20-TECHS/H76.html).

**Comment by marktopper** [comment]
I will make a pull request with configurations for this.

**Comment by marktopper** [comment]
I am thinking of making the configuration something like this:

```
docs:
  directory: docs
  url_prefix: /docs
  index: documentation
  default: installation
  redirect: false
```

Then it can be turned on for those who want this.
If turned on, then the page will become a redirection page instead of a copy of the original content.

The redirection will be done this way:
```
<!doctype html>
<html>
  <head>
    <title>{{ $siteName }}</title>
    <meta http-equiv="Refresh" content="0; url={{ $target }}">

    <script type="text/javascript">
      window.location.href = "{{ $target }}"
    </script>
  </head>

  <body>
  </body>
</html>
```

Thoughts?

**Comment by znck** [comment]
LGTM. Go ahead with PR. 👍

**Comment by marktopper** [comment]
Done with one of the parts at #4

**Comment by marktopper** [comment]
Pull request complete #4.
However, I have a odd configuration that I would like to add support for.

Structure:
```
.
+-- docs
|   +-- installation
|   |   +-- installation.md
|   |   +-- documentation.md
```

Would it be fine if there was no `installation.md` file, then it would redirect into the folder if such exists?
And of cause if `redirect` is turned of it should just show the content from `docs/installation/installation.md`.

**Comment by znck** [comment]
I'm cool with it.
